version: '3.3'

services:

# mysql database, not much extra setup needed.
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # user root 
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'localpass'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      - local-dev-network
    volumes:
      - local-db:/var/lib/mysql
  
  # nginx for our server. yeet
  web:
    image: nginx:latest
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./projects/code:/code
    ports:
      - "8080:80"
    networks:
      - local-dev-network
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  
  # php fpm container for our interpreter
  php:
    image: php:7-fpm
    container_name: php7
    networks:
      - local-dev-network
    volumes:
      - ./projects/code:/code

# adding a network to keep everything encapsulated
networks: 
  local-dev-network:
    driver: bridge

# Names our volume for mysql db
volumes:
  local-db: